const quotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "Do not watch the clock. Do what it does. Keep going. - Sam Levenson",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Dream big and dare to fail. – Norman Vaughan",
    "Action is the foundational key to all success. – Pablo Picasso",
    "Turn your wounds into wisdom. – Oprah Winfrey",
    "Everything you can imagine is real. – Pablo Picasso",
    "What you do today can improve all your tomorrows. – Ralph Marston",
    "Happiness depends upon ourselves. – Aristotle",
    "Don’t wait. The time will never be just right. – Napoleon Hill",
    "It always seems impossible until it’s done. – Nelson Mandela",
    "Start where you are. Use what you have. Do what you can. – Arthur Ashe",
    "If you can dream it, you can do it. – Walt Disney",
    "Quality is not an act, it is a habit. – Aristotle",
    "Opportunities don't happen. You create them. – Chris Grosser",
    "Do one thing every day that scares you. – Eleanor Roosevelt",
    "Great things never come from comfort zones.",
    "Push yourself, because no one else is going to do it for you.",
    "Success doesn’t just find you. You have to go out and get it.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Stay foolish to stay sane. – Maxime Lagacé",
    "Whatever you are, be a good one. – Abraham Lincoln",
    "The best way out is always through. – Robert Frost",
    "If opportunity doesn’t knock, build a door. – Milton Berle",
    "Don’t limit your challenges. Challenge your limits.",
    "Work hard in silence, let success make the noise.",
    "Doubt kills more dreams than failure ever will.",
    "Success is what comes after you stop making excuses.",
    "Make each day your masterpiece. – John Wooden",
    "Be so good they can’t ignore you. – Steve Martin",
    "Your limitation—it’s only your imagination.",
    "Great things take time.",
    "Stay focused and never give up.",
    "Difficult roads often lead to beautiful destinations.",
    "Don’t be afraid to give up the good to go for the great. – John D. Rockefeller",
    "Failure is the condiment that gives success its flavor. – Truman Capote",
    "The secret of getting ahead is getting started. – Mark Twain",
    "Believe in yourself and all that you are.",
    "You are stronger than you think.",
    "Success is not for the lazy.",
    "Small steps every day lead to big results.",
    "Consistency is what transforms average into excellence.",
    "Do it with passion or not at all.",
    "Stay positive, work hard, make it happen.",
    "Be yourself; everyone else is already taken. – Oscar Wilde",
    "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
    "Everything has beauty, but not everyone sees it. – Confucius",
    "He who has a why to live can bear almost any how. – Friedrich Nietzsche",
    "Act as if what you do makes a difference. It does. – William James",
    "The future depends on what you do today. – Mahatma Gandhi",

]
const button = document.querySelector('button');
const quote = document.querySelector('h1');
button.addEventListener('click', () => {
    const index = Math.floor(Math.random() * quotes.length);
    quote.textContent = quotes[index];
})